---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: buckets.storage.example.org
spec:
  connectionSecretKeys:
    - username
    - password
    - endpoint
  crdSpecTemplate:
    group: storage.example.org
    version: v1alpha1
    names:
      kind: Bucket
      listKind: BucketList
      plural: buckets
      singular: bucket
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters