apiVersion: storage.example.org/v1alpha1
kind: BucketRequirement
metadata:
  name: my-bucket
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  writeConnectionSecretToRef:
    name: bucket-conn
