---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: redisclusters.cache.example.org
spec:
  infrastructureDefinitionRef:
    name: redisclusters.cache.example.org