apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buckets.storage.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - storage.example.org
  resources:
  - buckets
  - buckets/status
  - bucketrequirements
  - bucketrequirements/status
  verbs:
  - "*"
