apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclusters.cache.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - cache.example.org 
  resources:
  - redisclusters
  - redisclusters/status
  - redisclusterrequirements
  - redisclusterrequirements/status
  verbs:
  - "*"
