apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlinstances.database.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - database.example.org
  resources:
  - postgresqlinstances
  - postgresqlinstances/status
  - postgresqlinstancerequirements
  - postgresqlinstancerequirements/status
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buckets.storage.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - storage.example.org
  resources:
  - buckets
  - buckets/status
  - bucketrequirements
  - bucketrequirements/status
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclusters.cache.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - cache.example.org
  resources:
  - redisclusters
  - redisclusters/status
  - redisclusterrequirements
  - redisclusterrequirements/status
  verbs:
  - "*"
