apiVersion: aws.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: aws-provider
  namespace: {{ .Values.namespace | default "default" | quote }}
spec:
  region: {{ .Values.region | quote }}
  credentialsSecretRef:
    namespace: crossplane-system
    name: aws-creds
    key: key
