apiVersion: storage.example.org/v1alpha1
kind: BucketRequirement
metadata:
  name: {{ .Values.bucketName }}
  namespace: default
spec:
  parameters:
    name: {{ .Values.bucketName }}
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.s3Secret }}
    namespace: default
---
apiVersion: cache.example.org/v1alpha1
kind: RedisClusterRequirement
metadata:
  name: my-redis
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.redisSecret }}
    namespace: default
---
apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstanceRequirement
metadata:
  name: my-db
  namespace: default
spec:
  parameters:
    storageGB: 10
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: {{ .Values.postgresSecret }}
    namespace: default