bucketName: 'quay.demo.octo.redhat.com' # make sure to change the bucket name
namespace: default # ensure that the region is the same as the variables.env file

# the secret names should also be the same as the variables.env file.
s3Secret: 'bucket-conn'
redisSecret: 'redis-conn'
postgresSecret: 'db-conn'
pullSecret: 'redhat-quay-pull-secret'

region: 'us-east-1' # change the region if needed
# with no VPC provided, Crossplane will create a VPC
# with no IGW provided, Crossplane will create an Internet Gateway

# the CIDR blocks were chosen based on the default subnets used by the openshift-install
# utility. You may need to configure this based on your VPC setup.   
aZCIDRa: '10.0.99.0/24'
aZCIDRb: '10.0.100.0/24'
aZCIDRc: '10.0.101.0/24'

# Switch this boolean to be false if you would like to use a 
# Redis cluster hosted within Kubernetes.
externalCache: false # we set this to false, since redis doesn't allow access outside of a VPC