---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpcpostgresqlinstances.aws.database.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: vpc-03167a922724e3b89
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
  to:
    - base:
        apiVersion: network.aws.crossplane.io/v1alpha3
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: us-east-2a
        spec:
          cidrBlock: 10.0.96.0/24
          vpcId: vpc-03167a922724e3b89
          availabilityZone: us-east-2a
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: network.aws.crossplane.io/v1alpha3
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: us-east-2b
        spec:
          cidrBlock: 10.0.97.0/24
          vpcId: vpc-03167a922724e3b89
          availabilityZone: us-east-2b
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: network.aws.crossplane.io/v1alpha3
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: us-east-2c
        spec:
          cidrBlock: 10.0.98.0/24
          vpcId: vpc-03167a922724e3b89
          availabilityZone: us-east-2c
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchControllerRef: true
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: network.aws.crossplane.io/v1alpha3
        kind: RouteTable
        spec:
          vpcId: vpc-03167a922724e3b89
          routes:
            - destinationCidrBlock: 0.0.0.0/0
              gatewayId: igw-05922aa399c27bf42
          associations:
            - subnetIdSelector:
                matchLabels:
                  desc: postgres
                  zone: us-east-2a
            - subnetIdSelector:
                matchLabels:
                  desc: postgres
                  zone: us-east-2b
            - subnetIdSelector:
                matchLabels:
                  desc: postgres
                  zone: us-east-2c
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: network.aws.crossplane.io/v1alpha3
        kind: SecurityGroup
        spec:
          vpcId: vpc-03167a922724e3b89
          groupName: crossplane-postgres
          description: Allow access to PostgreSQL
          ingress:
            - fromPort: 5432
              toPort: 5432
              protocol: tcp
              cidrBlocks:
                - cidrIp: 0.0.0.0/0
                  description: Everywhere
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            vpcSecurityGroupIDSelector:
              matchControllerRef: true
            dbInstanceClass: db.t2.small
            masterUsername: masteruser
            engine: postgres
            engineVersion: "9.6"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: postgres-secret-internal
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - name: database-username
          fromConnectionSecretKey: username
        - name: database-password
          fromConnectionSecretKey: password
        - name: database-root-password
          value: postgrestest
        - name: database-name
          value: postgres
        - name: server
          fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port