bucketName: 's3buckettestquayredhat'
namespace: default

s3Secret: 'bucket-conn'
redisSecret: 'redis-conn'
postgresSecret: 'db-conn'
pullSecret: 'redhat-quay-pull-secret'

region: 'us-east-2'
vpcId: 'vpc-009b237d62ab5e6c4'
igwId: 'igw-0a1a3844839765448'
aZCIDRa: '10.0.99.0/24'
aZCIDRb: '10.0.100.0/24'
aZCIDRc: '10.0.101.0/24'

# Switch this boolean to be false if you would like to use a 
# Redis cluster hosted within Kubernetes.
externalCache: true