---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: buckets.storage.example.org
spec:
  connectionSecretKeys:
    - host
    - secretKey
    - accessKey
    - bucketName
  crdSpecTemplate:
    group: storage.example.org
    version: v1alpha1
    names:
      kind: Bucket
      listKind: BucketList
      plural: buckets
      singular: bucket
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: buckets.storage.example.org
spec:
  infrastructureDefinitionRef:
    name: buckets.storage.example.org
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: buckets.aws.storage.example.org
  labels:
    provider: aws
    guide: quickstart
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: storage.example.org/v1alpha1
    kind: Bucket
  to:
    - base:
        apiVersion: storage.aws.crossplane.io/v1alpha3
        kind: S3Bucket
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
        spec:
          localPermission: ReadWrite
          region: {{ .Values.region }}
          cannedACL: private
          writeConnectionSecretToRef: 
            namespace: crossplane-system
            name: bucket-internal-secret
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
      connectionDetails:
        - name: host
          fromConnectionSecretKey: endpoint
        - name: accessKey
          fromConnectionSecretKey: username
        - name: secretKey
          fromConnectionSecretKey: password
    - base:
        apiVersion: storage.aws.crossplane.io/v1alpha1
        kind: S3BucketPolicy
        metadata:
          namespace: {{ .Values.namespace | default "default" | quote }}
          name: bucketPolicy
        spec:
          forProvider:
            bucketNameSelector: 
              matchControllerRef: true
            userNameSelector: 
              matchControllerRef: true
            statement:
              - action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:ListBucketMultipartUploads
                  - s3:PutBucketCORS
                effect: Allow
                effectIAMUser: true
                principal:
                  aws: []
                resource:
                  - {{ printf "%s" .Values.bucketName }}
              - effect: Allow
                effectIAMUser: true
                action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                resource:
                  - {{ printf "%s/*" .Values.bucketName }}
                principal:
                  aws: []
            version: '2012-10-17'
            name: aws-provider
          reclaimPolicy: Delete
          providerRef:
            name: aws-provider