---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  connectionSecretKeys:
    - database-username
    - database-password
    - database-root-password
    - database-name
    - database-server
    - port
  crdSpecTemplate:
    group: database.example.org
    version: v1alpha1
    names:
      kind: PostgreSQLInstance
      listKind: PostgreSQLInstanceList
      plural: postgresqlinstances
      singular: postgresqlinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  storageGB:
                    type: integer
                required:
                  - storageGB
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: postgresqlinstances.database.example.org
spec:
  infrastructureDefinitionRef:
    name: postgresqlinstances.database.example.org
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpcpostgresqlinstances.aws.database.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: {{ .Values.vpcId }}
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: database.example.org/v1alpha1
    kind: PostgreSQLInstance
  to:
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: {{ printf "%sa" .Values.region }}
        spec:
          forProvider:
            cidrBlock: 10.0.96.0/24
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sa" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: {{ printf "%sb" .Values.region }}
        spec:
          forProvider:
            cidrBlock: 10.0.97.0/24
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sb" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: postgres
            zone: {{ printf "%sc" .Values.region }}
        spec:
          forProvider:
            cidrBlock: 10.0.98.0/24
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sc" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        spec:
          forProvider:
            description: An excellent formation of subnetworks.
            subnetIdSelector:
              matchControllerRef: true
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1alpha4
        kind: RouteTable
        spec:
          forProvider:
            vpcId: {{ .Values.vpcId }}
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayId: {{ .Values.igwId }}
            associations:
              - subnetIdSelector:
                  matchLabels:
                    desc: postgres
                    zone: {{ printf "%sa" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: postgres
                    zone: {{ printf "%sb" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: postgres
                    zone: {{ printf "%sc" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            vpcId: {{ .Values.vpcId }}
            groupName: crossplane-postgres
            description: Allow access to PostgreSQL
            ingress:
            - fromPort: 5432
              toPort: 5432
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        spec:
          forProvider:
            dbSubnetGroupNameSelector:
              matchControllerRef: true
            vpcSecurityGroupIDSelector:
              matchControllerRef: true
            dbInstanceClass: db.t2.small
            masterUsername: masteruser
            engine: postgres
            engineVersion: "9.6"
            skipFinalSnapshotBeforeDeletion: true
            publiclyAccessible: true
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: postgres-secret-internal
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
      patches:
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-postgresql"
        - fromFieldPath: "spec.parameters.storageGB"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - name: database-username
          fromConnectionSecretKey: username
        - name: database-password
          fromConnectionSecretKey: password
        - name: database-root-password
          value: postgrestest
        - name: database-name
          value: postgres
        - name: database-server
          fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
