---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: networkgroups.ec2.example.org
spec:
  crdSpecTemplate:
    group: ec2.example.org
    version: v1alpha1
    names:
      kind: NetworkGroup
      listKind: NetworkGroupList
      plural: networkgroups
      singular: networkgroup
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: networkgroups.ec2.example.org
spec:
  infrastructureDefinitionRef:
    name: networkgroups.ec2.example.org
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: vpcnetworkgroups.aws.ec2.example.org
  labels:
    provider: aws
    guide: quickstart
    vpc: {{ .Values.vpcId }}
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  from:
    apiVersion: ec2.example.org/v1alpha1
    kind: NetworkGroup
  to:
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: quay
            zone: {{ printf "%sa" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRa }}
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sa" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: quay
            zone: {{ printf "%sb" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRb }}
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sb" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            desc: quay
            zone: {{ printf "%sc" .Values.region }}
        spec:
          forProvider:
            cidrBlock: {{ .Values.aZCIDRc }}
            vpcId: {{ .Values.vpcId }}
            availabilityZone: {{ printf "%sc" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1alpha4
        kind: RouteTable
        spec:
          forProvider:
            vpcId: {{ .Values.vpcId }}
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayId: {{ .Values.igwId }}
            associations:
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sa" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sb" .Values.region }}
              - subnetIdSelector:
                  matchLabels:
                    desc: quay
                    zone: {{ printf "%sc" .Values.region }}
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            desc: quay
        spec:
          forProvider:
            vpcId: {{ .Values.vpcId }}
            groupName: crossplane-quay
            description: Allow access to Quay dependencies
            ingress:
            - fromPort: 6379
              toPort: 6379
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
            - fromPort: 5432
              toPort: 5432
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
            egress:
            - fromPort: 6379
              toPort: 6379
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
          providerRef:
            name: aws-provider
          reclaimPolicy: Delete