---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructureDefinition
metadata:
  name: redisinstances.cache.example.org
spec:
  connectionSecretKeys:
    - endpoint
    - port
  crdSpecTemplate:
    group: cache.example.org
    version: v1alpha1
    names:
      kind: RedisInstance
      listKind: RedisInstanceList
      plural: redisinstances
      singular: redisinstance
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object