apiVersion: cache.example.org/v1alpha1
kind: RedisClusterRequirement
metadata:
  name: my-redis
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: new
  writeConnectionSecretToRef:
    name: redis-conn