apiVersion: storage.aws.crossplane.io/v1alpha3
kind: S3Bucket
metadata:
  name: s3bucket-test-quay.krish.redhat.com
  labels:
    demo: test 
spec:
  localPermission: ReadWrite
  region: us-east-2
  cannedACL: private
  writeConnectionSecretToRef:
    name: s3bucket
    namespace: crossplane-system
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider