---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: InfrastructurePublication
metadata:
  name: buckets.storage.example.org
spec:
  infrastructureDefinitionRef:
    name: buckets.storage.example.org